[2022-08-28 23:51:37,481] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:51:36.098989+00:00 [queued]>
[2022-08-28 23:51:37,489] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:51:36.098989+00:00 [queued]>
[2022-08-28 23:51:37,489] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:51:37,489] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-28 23:51:37,489] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:51:37,498] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): check_taxigov_data> on 2022-08-28 23:51:36.098989+00:00
[2022-08-28 23:51:37,501] {standard_task_runner.py:52} INFO - Started process 4173 to run task
[2022-08-28 23:51:37,502] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_and_populate_taxigov_datawarehouse', 'check_taxigov_data', 'manual__2022-08-28T23:51:36.098989+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/create_and_populate_taxigov_datawarehouse_dag.py', '--cfg-path', '/tmp/tmp5wmkjre4', '--error-file', '/tmp/tmpezu7rbrm']
[2022-08-28 23:51:37,503] {standard_task_runner.py:80} INFO - Job 153: Subtask check_taxigov_data
[2022-08-28 23:51:37,545] {task_command.py:371} INFO - Running <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:51:36.098989+00:00 [running]> on host ddc8002727e0
[2022-08-28 23:51:37,601] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_and_populate_taxigov_datawarehouse
AIRFLOW_CTX_TASK_ID=check_taxigov_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T23:51:36.098989+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-28T23:51:36.098989+00:00
[2022-08-28 23:51:37,612] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-28 23:51:39,491] {create_and_populate_taxigov_datawarehouse_dag.py:20} INFO - Data Quality for table raw__taxigov_corridas checks passed.
[2022-08-28 23:51:39,492] {python.py:173} INFO - Done. Returned value was: None
[2022-08-28 23:51:39,501] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=create_and_populate_taxigov_datawarehouse, task_id=check_taxigov_data, execution_date=20220828T235136, start_date=20220828T235137, end_date=20220828T235139
[2022-08-28 23:51:39,519] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-28 23:51:39,540] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
