[2022-08-28 23:47:42,814] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:47:41.658303+00:00 [queued]>
[2022-08-28 23:47:42,820] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:47:41.658303+00:00 [queued]>
[2022-08-28 23:47:42,820] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:47:42,820] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-28 23:47:42,820] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:47:42,829] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): check_taxigov_data> on 2022-08-28 23:47:41.658303+00:00
[2022-08-28 23:47:42,832] {standard_task_runner.py:52} INFO - Started process 3960 to run task
[2022-08-28 23:47:42,835] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_and_populate_taxigov_datawarehouse', 'check_taxigov_data', 'manual__2022-08-28T23:47:41.658303+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/create_and_populate_taxigov_datawarehouse_dag.py', '--cfg-path', '/tmp/tmpz48tslgk', '--error-file', '/tmp/tmpacytbw7x']
[2022-08-28 23:47:42,835] {standard_task_runner.py:80} INFO - Job 143: Subtask check_taxigov_data
[2022-08-28 23:47:42,877] {task_command.py:371} INFO - Running <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:47:41.658303+00:00 [running]> on host ddc8002727e0
[2022-08-28 23:47:42,927] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_and_populate_taxigov_datawarehouse
AIRFLOW_CTX_TASK_ID=check_taxigov_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T23:47:41.658303+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-28T23:47:41.658303+00:00
[2022-08-28 23:47:42,934] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-28 23:47:45,402] {create_and_populate_taxigov_datawarehouse_dag.py:20} INFO - Data Quality for table raw__taxigov_corridas checks passed.
[2022-08-28 23:47:45,402] {python.py:173} INFO - Done. Returned value was: None
[2022-08-28 23:47:45,414] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=create_and_populate_taxigov_datawarehouse, task_id=check_taxigov_data, execution_date=20220828T234741, start_date=20220828T234742, end_date=20220828T234745
[2022-08-28 23:47:45,455] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-28 23:47:45,487] {local_task_job.py:273} INFO - 3 downstream tasks scheduled from follow-on schedule check
