[2022-08-28 23:58:48,586] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:58:47.937576+00:00 [queued]>
[2022-08-28 23:58:48,593] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:58:47.937576+00:00 [queued]>
[2022-08-28 23:58:48,593] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:58:48,593] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-28 23:58:48,593] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:58:48,603] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): check_taxigov_data> on 2022-08-28 23:58:47.937576+00:00
[2022-08-28 23:58:48,606] {standard_task_runner.py:52} INFO - Started process 4523 to run task
[2022-08-28 23:58:48,608] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_and_populate_taxigov_datawarehouse', 'check_taxigov_data', 'manual__2022-08-28T23:58:47.937576+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/create_and_populate_taxigov_datawarehouse_dag.py', '--cfg-path', '/tmp/tmpjjkoqqbj', '--error-file', '/tmp/tmpltss6vym']
[2022-08-28 23:58:48,608] {standard_task_runner.py:80} INFO - Job 158: Subtask check_taxigov_data
[2022-08-28 23:58:48,648] {task_command.py:371} INFO - Running <TaskInstance: create_and_populate_taxigov_datawarehouse.check_taxigov_data manual__2022-08-28T23:58:47.937576+00:00 [running]> on host ddc8002727e0
[2022-08-28 23:58:48,701] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_and_populate_taxigov_datawarehouse
AIRFLOW_CTX_TASK_ID=check_taxigov_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T23:58:47.937576+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-28T23:58:47.937576+00:00
[2022-08-28 23:58:48,708] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-28 23:58:50,284] {create_and_populate_taxigov_datawarehouse_dag.py:20} INFO - Data Quality for table raw__taxigov_corridas checks passed.
[2022-08-28 23:58:50,289] {python.py:173} INFO - Done. Returned value was: None
[2022-08-28 23:58:50,299] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=create_and_populate_taxigov_datawarehouse, task_id=check_taxigov_data, execution_date=20220828T235847, start_date=20220828T235848, end_date=20220828T235850
[2022-08-28 23:58:50,343] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-28 23:58:50,365] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
